basePath: /internal/v1
host: localhost:8080
info:
  contact:
    email: vatusa6@vatusa.net
    name: VATUSA Support
    url: http://www.swagger.io/support
  description: VATUSAs internal API for use by other internal VATUSA services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VATUSA Internal
  version: "0.1"
paths: {}
swagger: "2.0"
