name: lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    branches:
      - '*'

jobs:
  test:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --timeout=5m